### ISSUE TITLE
Warn user if they create a new geometry that is far from their geolocation

### ISSUE THREAD

**Issue by spwoodcock** [hotosm/fmtm#1988] opened 2024-12-12 14:59 UTC
**Is your feature request related to a problem? Please describe.**

- If the user clicks to create a new map feature, but the point is very far from their location, we should warn them.

**Describe the solution you'd like**

- Currently when the user clicks for the point, it redirects to ODK Collect immediately.
- We should add a check before that:
  - `if geolocation is enabled` && `if clicked point is more than 50m from current location`, do not redirect.
  - Instead open a confirmation dialog / modal: 'The created geometry is far away from your current location. Are you sure you wish to proceed?'
  - If the user clicks 'Yes', then continue with the ODK Collect redirect / intent, if 'No', then remove the point from the map (but keep drawing enabled!)

**Comment by manjitapandey** [comment] 2024-12-13 04:50
duplicate of #1985

**Comment by spwoodcock** [comment] 2024-12-13 10:10
Thanks!

Closing this

**Closed** 2024-12-13 10:10 UTC
Labels: enhancement, priority:low, frontend, effort:low
