### ISSUE TITLE
The search field should apply for all the projects search

### ISSUE THREAD

**Issue by susmina94** [hotosm/fmtm#983] opened 2023-11-08 11:27 UTC
**Describe the bug**

I had a project in FMTM, I could see the project card in page 2.
But if I searched for the project while I was in page 1 
It showed no results found.

I switched to page 2 and searched for the project, I could see the project.

**Expected behavior**
The projects should be searchable within the list of projects despite the pagination.

**Screenshots**

![Image](https://github.com/hotosm/fmtm/assets/108750444/909aca77-b4e8-477e-b58f-fd26b2dd1aa8)

![Image](https://github.com/hotosm/fmtm/assets/108750444/352d5a92-79fd-4389-a06b-f7e97ed38f3f)

**Comment by spwoodcock** [comment] 2023-11-08 11:29
I just made an issue for this 😁 #981

**Comment by spwoodcock** [comment] 2023-11-08 11:30
Feel free to close either. It's to do with the new pagination addition.

**Comment by susmina94** [comment] 2023-11-20 04:56
#981 Duplicate to this issue

**Comment by varun2948** [comment] 2023-11-21 11:04
Duplicate of #981

**Closed** 2023-11-21 11:05 UTC
Labels: bug, frontend, backend
