### ISSUE TITLE
2024-07-04 Sierra Leone project creation journey

### ISSUE THREAD

**Issue by ivangayton** [hotosm/fmtm#1625] opened 2024-07-04 05:51 UTC
# Freetown, Sierra Leone FMTM Project creation

Building an FMTM project from an existing building enumeration project by a community in Freetown, Sierra Leone, as part of a World Bank-funded Know Your City initiative.

The community is already quite sophisticated, and they have their own very elaborate data collection form that they've been using. This exercise is to move their existing campaign over to an FMTM setup.

I've created a Google Drive folder containing the AOI, the form created by the community, and my attempt at merging their form with the FMTM default building form. [Here's the folder](https://drive.google.com/drive/folders/1uT9NX5v_fGxsS5-Ngv2gFh0TWigpg_u_?usp=sharing).

The OpenAerialMap imagery is at the TMS ```https://tiles.openaerialmap.org/663c76196049ef00013b8494/0/663c76196049ef00013b8495/{z}/{x}/{y}```. The actual dataset page to view in OAM is [here](https://map.openaerialmap.org/#/-13.240637499999995,8.487964506432862,18/square/03332112322301031013/663c78866049ef00013b8497?_k=uk5x8r).

Steps are:
- Getting drone imagery covering the relevant area up on OpenAerialMap
- Digitizing high-quality building footprints within that area, getting those footprints onto OSM
- Converting the community's XLSForm to work with the FMTM, which basically means merging it with the default FMTM building form that works with the buildings and entities
- Creating an FMTM project
- Extracting MBTiles for the area

## Merging a form with the FMTM default building form

Modify the default FMTM building form ("FMTM Form") to include the survey questions from a form designed by a user with an existing ODK form ("Client Form"), 

### Steps taken
- Start creating a project on FMTM prod site. Choose buildings, custom XLSForm, download template ```form.xls```. Make a copy of this to serve as the FMTM Form with a name relevant to your specific project.
- In the copy of the FMTM Form, unhide the top rows, delete everything on Survey tab below line 30 ("Edit below here")
- Copy the entire contents—including the header row—of the ```survey``` tab from the Client Form
- Paste it as unformatted text (```shift-control-V``` and choose "Unformatted text") into the ```survey``` tab of the FMTM Form below line 30, _to the right of all of the columns in the FMTM Form_ (therefore starting on column V, this is so we can move each column into its proper place without overwriting other columns).
- For each column, select the pasted data from the Client Form in the FMTM Form from the header row (presumably row 31 or 32, depending if you left a space after the "Edit below here" row). Move each column so that it's directly below the corresponding header at the top of the FMTM Form (this should be easy since the FMTM Form's first row is frozen by default).
  - If the Client Form doesn't have multilingual headers, place the Name and Hint data below the relevant-language FMTM Form headers (for example, the ```name``` data from and English-language Client Form would go under the ```label::English(en)``` header).
  - If there's a header in the Client Form that doesn't correspond to any of the headers in the FMTM Form, add it to the right of the FMTM Form headers, and copy the column name into Row 1.
- Once all of the data from the Client Form is in the correct place the FMTM Form template, delete the header row copied in from the Client Form.
- Do the same process for the ```choices``` tab.
- It's a good idea to change the ```form_id``` and ```form_title``` in the ```settings``` tab to something related to your project; this can help keep track of different form versions since ODK and FMTM don't normally display anything related to the filename, they understand form versions based on the contents of the ```settings``` tab.

## Create the FMTM project
- Name etc
- Choose ```Custom TMS``` and add the TMS from OpenAerial Map 
- Choose 10 features per task
- 

## Create the MBTiles

Hit the ```basemaps``` button. The dialogue appears, already properly populated with the OAM TMS from the project creation dialogue. Choose MBTiles and push create.

# Shit that inevitably goes wrong
- Most importantly, after waiting 20 minutes, clicking on a polygon doesn't do much. No QR code or buildings displayed.
  - Maybe I didn't wait long enough, but even if that's the case, it would be awesome to have some way of knowing that project creation is still ongoing, rather than wondering if it's done but not working. 
- During task creation, there's a weird set of extra polygons that appear out of nowhere. They didn't seem to affect anything, but would be nice to find out why it happened.
- The MBTile creation dialogue had the correct TMS URL and after a little while the status set to ```completed```, but the download button doesn't do anything. Not clear if the MBTiles were succesfully created or not.
  - The delete button just gives a "not implemented yet" popup
  - PMTiles give the same result as MBTiles: the status sets to "completed" after a few moments but the download button seems inert. A red lightning bolt appears next to the PMTiles row, which is interesting!

**Comment by spwoodcock** [comment] 2024-07-08 11:50
Thanks Ivan for the detailed post!

**Slow project creation**

- It seems that making an API call for every Entity (building / feature) to be created takes a long time for a remote ODK server.
- This isn't as much of an issue for dev / stage / instances with bundled ODK Collect.
- Either way, it will be fixed in the next release when the use the new bulk Entity creation API from ODK Collect.

**FMTM splitter issues**

- @Sujanadh is working on fmtm-splitter currently 👍 
- We will ensure that polygons with no buildings / features inside them get removed from the split areas (sometimes this happens).
- Others issues are tracked / fixes on hotosm/fmtm-splitter

**MBTiles issues**

- I have pushed a hotfix that solves the MBTiles download issue.
- We identified an issue in osm-fieldwork MBTiles generation where the max zoom level was capped for viewing at 18, despite the tiles being present for zooms 21-22. Fixed in osm-fieldwork & will be in the next FMTM release.
- The PMTiles work as intended - the lightning bolt icon mentioned is for downloading the file into OPFS browser storage and displaying entirely offline basemaps in FMTM.

Let us know how the project goes & keep the feedback coming!

**Closed by spwoodcock** 2024-07-08 11:50 UTC
Labels: bug
