### ISSUE TITLE
Creating task areas with no features should not be possible

### ISSUE THREAD

**Issue by Sujanadh** [hotosm/fmtm#1641] opened 2024-07-11 04:22 UTC
**Replica of issue on `fmtm-splitter`**

**Describe the bug**

- This is specific to the **split by square** algorithm.
- It's possible that sometimes a task area is generated with no features inside it.
- This happens when an AOI is not square.

**To Reproduce**

Project https://fmtm.hotosm.org/project/104

**Expected behavior**

- The task areas with no features are deleted at the end of the `split_by_square` function to avoid this problem.

**Screenshots**

You can see two small task areas that have no buildings:
![image](https://github.com/hotosm/fmtm-splitter/assets/78538841/6968392e-4dc3-4cc5-b52a-e1cdf22f8be5)

**Additional considerations**

I imagine this problem does not exist on the complex splitting algorithm, as we handle the case already.

**Comment by manjitapandey** [comment] 2024-07-17 07:59
I am confused. I created the project as instructed above. I choosed the building as form category and splitted task by square. But some task square are created where there is no building feature but contains other features like riverways and roadways. Is the requirement here is not to create the task if there is no feature within it or the task won't be created if there is no building feature within. 

for Reference: https://dev.fmtm.hotosm.org/project/41

**Comment by spwoodcock** [comment] 2024-07-17 08:07
I think you are right - related to https://github.com/hotosm/fmtm-splitter/issues/44

**Comment by manjitapandey** [comment] 2024-07-17 08:29
If so, the issue is fixed. Closing this for now.

**Closed by manjitapandey** 2024-07-17 08:29 UTC
Labels: bug, priority:high, backend, testing:ready, dependency:fmtm-splitter

**Comment by spwoodcock** [comment] 2024-07-17 15:26
You are right we need to decide on the configuration we will provide in the new project creation flow.

Currently it's mandatory for the user to include linestrings in their data extract for the splitting algorithm to work, but we definitely don't want this as the default going forward.

I think we should re-design how things work in https://github.com/hotosm/fmtm/milestone/38

- Users should be able to upload a data extract of only buildings.
- The split by square and split by sql modes should 'just work', meaning we handle downloading the linestrings if necessary.

With this in mind, the data extract should only contain the features to be mapped in all cases (downloaded, or custom upload).

Then `split_by_square` should:
- Have the option in fmtm-splitter to take no data extract.
- However, we always pass through a data extract from FMTM, whether downloaded or custom upload.
- The data extract (containing only the features to be mapped, no linestrings) is used to determined if the square is removed from the final tasks (if no features are present in the square).

And `split_by_sql` should have user configuration on the frontend:
- Always take the data extract, either downloaded or custom upload.
- If the category is a type of linestring, e.g. mapping roads, we disable the splitting algorithm until we think of a solution.
- If the category is a type of polgon, e.g. buildings, we enable the splitting algorithm.
- We ask the user for input with a set of checkboxes for type of linestring they want to split by:
  - [ ] major roads
  - [ ] minor roads
  - [ ] rivers
  - [ ] railways
  - [ ] airstrips
- These linestrings are downloaded by `fmtm-splitter` during the splitting process, and the split tasks are returned.

Can you see any flaws in this approach @Sujanadh?

**Comment by Sujanadh** [comment] 2024-07-18 07:14
seems good to me. But the checkboxes for type of linestring can be large.
https://wiki.openstreetmap.org/wiki/Key:highway
