### ISSUE TITLE
Integrate hotosm/conflator conflatePOI for conflation (replace odk_merge)

### ISSUE THREAD

**Issue by susmina94** [hotosm/fmtm#855] opened 2023-09-26 18:21 UTC
#Problem

I use the convert to JOSM tool, but the data that appear aren't the geometry of features instead the GPS location of the form submissions.

#Actual Behavior

The data should show the geometry of features in the data extract that's selected (Polygon or centroid or line)

**Edit 21.11.2023** updated issue to use new conflator repo, as should solve issue.

**Comment by robsavoye** [comment] 2023-09-27 07:34
For more detail, try the odk_merge.py program, and see if the problem is in the UI, or the conflation. If it's a conflation issue, give me the project kink on Central so I can grab the JSON file.

**Comment by robsavoye** [comment] 2023-10-13 18:26
Was the original data selected from a data extract in Collect, or without one ?

**Comment by robsavoye** [comment] 2023-11-07 19:27
I finally got my standalone python module for conflation working. The POI conflation code is all from odk_merge. It needs a little cleanup and a test case, but after that we can use this instead of odk_merge. The new code is at:
https://github.com/hotosm/conflator

**Comment by spwoodcock** [comment] 2023-11-08 08:25
Nice! We will add it in soon & see if it solves the issues Susmina was having (I will test too) 👍

**Comment by robsavoye** [comment] 2023-11-26 21:43
The one downside now is to fully work it needs a local postgres database that has been imported with the refs for ways. This will get added to osm-raw-data for remote queries, but not sure when that will be done.

**Comment by spwoodcock** [comment] 2023-11-26 23:24
You mean the conflator repo will actually get integrated into raw-data-api, then we will query that instead?

So in the long run we will use osm-rawdata to handle this.

Depending on timeframes, one solution for now could be to add a foreign data wrapper to the FMTM database and use the local query to get the data directly from the underlying database for raw-data-api (we would need to ask for credentials though).

**Comment by robsavoye** [comment] 2023-11-26 23:37
conflator right now works only in a local postgres since raw-data-api doesn't support spatial queries, for example, give me all buildings within 10 meters. Also raw-data-api needs to store the refs, since they are required to generate a working OSM XML file for JOSM. So for now, conflation will need to be a manual operation till osm-raw-data catches up, and I don't think this will be soon. So we should integrate conflator, as it works much better than odk_merge now. raw-data-api doesn't use credentials, so that's easy. To use conflator with FMTM now, we'd need to front-load the country into postgres using the importer program in osm-rawdata.

As of a few days ago, conflator was successfully merging tags from ODK Collect (which are a POI) into the building polygon when there is a match.

**Comment by spwoodcock** [comment] 2023-11-27 02:25
Until there is support via the raw-data-api JSON / API, and instead of having to load the data into our local postgres everytime, could we just be given read only credentials to the underlying raw-data-api database?

We could even use a foreign data wrapper on the FMTM database if it helps to fit with the code.

**Comment by spwoodcock** [comment] 2024-06-05 10:49
Superseded by https://github.com/hotosm/fmtm/issues/1548, closing.

**Closed by spwoodcock** 2024-06-05 10:49 UTC
Labels: Priority: Should have, backend
