### ISSUE TITLE
Issues for displaying the QR in the project's page

### ISSUE THREAD

**Issue by emi420** [hotosm/fmtm#1620] opened 2024-07-02 16:20 UTC
**Describe the bug**
I've just created a project and when I click on a task to display the QR so I can scan it with my phone the selection is failing. 

**To Reproduce**

1. Open a project
2. Click on a task
3. Buildings from another task are selected or a building is selected instead of the task

**Expected behavior**

Select the buildings inside the selected task. Not select a building if a click on an empty area.

**Screenshots**

https://github.com/hotosm/fmtm/assets/1226194/efaaf64d-e79c-4c4a-bfa4-fa956f74499e

**Additional context**

Browser: Firefox 127.0.2

**Comment by spwoodcock** [comment] 2024-07-03 14:25
Thanks @emi420 👍

@manjitapandey @ramyaragupathy 
as the QR Code is now for the entire project and not per task, should we move the QR code to somewhere else in the UI?

The task locking could also be done in the sidebar instead of via popup.

Then we will only have buildings / features with popup on click

**Comment by spwoodcock** [comment] 2024-07-22 11:21
Actually this isn't the error I was originally imagining.

@manjitapandey @NSUWAL123 could we please try to replicate this issue and debug?

**Comment by manjitapandey** [comment] 2024-07-23 08:02
I also couldn't replicate this behavior, May be some further infos can help us dig in better.

**Comment by spwoodcock** [comment] 2024-07-23 08:10
It is possible it's been fixed since!

But we can test on the original project.

I think it might have been deleted and replaced with this though: https://fmtm.hotosm.org/project/104

**Comment by manjitapandey** [comment] 2024-07-23 08:17
Yeah the project has been deleted and I tested both on prod and dev server and couldn't replicate the issue. If the issue is reported again we can reopen it. closing this issue for now.

**Closed by manjitapandey** 2024-07-23 08:17 UTC
Labels: bug, priority:high, frontend, effort:low
